host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: 'pipfile-cve'
    operating_system:
      name: rhel
      version: '8'
    python_version: '3.8'

  - name: 'pipfile-no-cve'
    operating_system:
      name: rhel
      version: '8'
    python_version: '3.8'
