name: 'Thoth Adviser'
description: 'Get security recommendations for packages in a Python project and score its dependency stack.'
author: 'Thoth-Station'
inputs:
  requirementsFormat:
    description: 'Requirements format for the project dependencies, one of (pip | pip-tools | pip-compile | pipenv)'
    default: pipenv
env:
  THAMOS_NO_INTERACTIVE: True
on: 
  push:
    paths:
      - 'requirements.txt'
      - 'Pipfile'
jobs:
  get-advise:
    name: Get advise from Thoth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Read Pipfile
        id: Pipfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Pipfile
      - name: Echo Pipfile
        run: echo "${{ steps.Pipfile.outputs.content }}"
