name: 'Test the Thoth GitHub Action for dependencies in Pipfile format without CVE'
on:
  push:
    paths:
      - 'overlays/pipfile-no-cve/Pipfile'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advise
        id: thoth-advise
        uses: thoth-station/thoth-github-action@772240f40b55740d3d14e412fa07cb5ba841c1d3
        with:
          requirements-path: 'overlays/pipfile-no-cve/Pipfile'
          requirements-format: pipenv
          overlay-directory: pipfile-no-cve
