name: 'Test for Thoth GitHub Action'
on:
  push:
    paths:
      - 'requirements.txt'
      - 'Pipfile'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advisories
        id: thoth-advise
        uses: thoth-station/thoth-github-action@13068d981e2c6a882d54e32214f0de7e0887e1e4
        with:
          requirements-path: 'Pipfile'
          requirements-format: pipenv

