name: 'Test the Thoth GitHub Action for dependencies in setup.cfg format with CVE'
on:
  push:
    paths:
      - 'overlays/setup-cfg-cve/setup.cfg'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advise
        id: thoth-advise
        uses: thoth-station/thoth-github-action@24fa52d5e9db82b81410dfa00c112d375f48021d
        with:
          requirements-path: 'overlays/setup-cfg-cve/setup.cfg'
          requirements-format: setup.cfg
          overlay-directory: setup-cfg-cve
