name: 'Test the Thoth GitHub Action for dependencies in Pipfile format with CVE'
on:
  push:
    paths:
      - 'overlays/pipfile-cve/Pipfile'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advise
        id: thoth-advise
        uses: thoth-station/thoth-github-action@167eabc5f85c7041c7186cc95bd5e7c5443dc044
        with:
          requirements-path: 'overlays/pipfile-cve/Pipfile'
          requirements-format: pipenv
          overlay-directory: pipfile-cve
