name: 'Test for Thoth GitHub Action'
on:
  push:
    paths:
      - 'requirements.txt'
      - 'Pipfile'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommenations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advisories
        id: thoth-advise
        uses: thoth-station/thoth-github-action@a7567b95f0d07586070b04f31260ef2f9dbb6ef5
        with:
          requirements-path: 'Pipfile'
          requirements-format: pipenv
