name: 'Test the Thoth GitHub Action for dependencies in setup.cfg format without CVE'
on:
  push:
    paths:
      - 'overlays/setup-cfg-no-cve/setup.cfg'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Get Thoth security advise
        id: thoth-advise
        uses: thoth-station/thoth-github-action@d04fe9b74959385c014a4faa9e802f1e0e29f6fa
        with:
          requirements-path: 'overlays/setup-cfg-no-cve/setup.cfg'
          requirements-format: setup.cfg
          overlay-directory: setup-cfg-no-cve
