name: 'Test the Thoth GitHub Action for dependencies in pip/pip-tools/pip-compile format without CVE'
on:
  push:
    paths:
      - 'overlays/requirements-txt-no-cve/requirements.txt'
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advise
        id: thoth-advise
        uses: thoth-station/thoth-github-action@30cc40fe0c023167ce0b2f119aa070123b50373b
        with:
          requirements-path: 'overlays/requirements-txt-no-cve/requirements.txt'
          requirements-format: pip
          overlay-directory: requirements-txt-no-cve
